title: キュアスタ！Blog
description: ''
author: ぷーざ
lang: ja
timezone: Asia/Tokyo
url: https://pooza.github.io
baseurl: /curesta-blog

permalink: /articles/:title/

markdown: kramdown
kramdown:
  input: GFM

collections:
  drafts:
    output: false

exclude:
  - node_modules
  - package.json
  - yarn.lock
  - scaffolds
  - themes
  - _config.hexo.yml
  - source
  - public
